// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7jGFpf4s-wflGQSWlyUpSibhGaFI0U4',
    appId: '1:693006671110:web:0d3d934454df026478d287',
    messagingSenderId: '693006671110',
    projectId: 'flutter-chat-84bf2',
    authDomain: 'flutter-chat-84bf2.firebaseapp.com',
    storageBucket: 'flutter-chat-84bf2.appspot.com',
    measurementId: 'G-7Y9D4P542V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPCfm07kAdR07JvfKux-dtS0IdwjeVqE',
    appId: '1:693006671110:android:e229fdf48f5cdbd578d287',
    messagingSenderId: '693006671110',
    projectId: 'flutter-chat-84bf2',
    storageBucket: 'flutter-chat-84bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9z5KByhy2CaLkSNBEvmGVBVMEh7NZT30',
    appId: '1:693006671110:ios:4f6685f7ba61280978d287',
    messagingSenderId: '693006671110',
    projectId: 'flutter-chat-84bf2',
    storageBucket: 'flutter-chat-84bf2.appspot.com',
    androidClientId: '693006671110-919ltctu3lb99b4se64lk07tf2h5ttcq.apps.googleusercontent.com',
    iosClientId: '693006671110-bnkqefc2850ih5sh62fjats47h37u3jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9z5KByhy2CaLkSNBEvmGVBVMEh7NZT30',
    appId: '1:693006671110:ios:4f6685f7ba61280978d287',
    messagingSenderId: '693006671110',
    projectId: 'flutter-chat-84bf2',
    storageBucket: 'flutter-chat-84bf2.appspot.com',
    androidClientId: '693006671110-919ltctu3lb99b4se64lk07tf2h5ttcq.apps.googleusercontent.com',
    iosClientId: '693006671110-bnkqefc2850ih5sh62fjats47h37u3jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
